import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../services/fridge_service.dart';
import '../services/icon_generator_service.dart';
import '../theme/app_theme.dart';

/// Smart item icon — fallback chain:
/// 1. Bundled asset  (assets/icons/{key}.png)  — instant, no network
/// 2. Firebase Storage (icons/{key}.jpg)        — 350×350 baseline set shared
///    with the CH display board (what the app generates now)
/// 3. Firebase Storage (icons/{key}.png)        — legacy PNGs from the old pipeline
/// 4. Gemini AI generation                      — for new items
/// 5. Coloured letter avatar                    — last resort
class ItemIcon extends StatefulWidget {
  final String itemName;
  final double size;
  final BorderRadius? borderRadius;

  const ItemIcon({
    super.key,
    required this.itemName,
    this.size = 52,
    this.borderRadius,
  });

  @override
  State<ItemIcon> createState() => _ItemIconState();
}

class _ItemIconState extends State<ItemIcon> {
  /// Bundled asset bytes — loaded once, cached here
  Uint8List? _asset;
  bool _assetChecked = false;

  /// Gemini-generated bytes
  Uint8List? _generated;
  bool _generating = false;
  bool _generationFailed = false;

  /// Bundled assets ship as lowercase filenames (assets/icons/milk.png), so
  /// that lookup stays lowercased. Storage objects use the item's exact name.
  String get _assetKey => widget.itemName.toLowerCase().trim();

  @override
  void initState() {
    super.initState();
    _loadAsset();
  }

  @override
  void didUpdateWidget(ItemIcon old) {
    super.didUpdateWidget(old);
    // Grid cells are reused for different items when the list reorders or
    // filters — without this reset the old item's image sticks around.
    if (old.itemName != widget.itemName) {
      setState(() {
        _asset = null;
        _assetChecked = false;
        _generated = null;
        _generating = false;
        _generationFailed = false;
      });
      _loadAsset();
    }
  }

  Future<void> _loadAsset() async {
    try {
      final data =
          await rootBundle.load('assets/icons/$_assetKey.png');
      final bytes = data.buffer.asUint8List();
      // The fridge screen can only read Firebase Storage, so publish the
      // bundled art once — otherwise common items stay blank on the TFT.
      IconGeneratorService.ensureStorageIcon(widget.itemName, bytes);
      if (mounted) {
        setState(() {
          _asset = bytes;
          _assetChecked = true;
        });
      }
    } catch (_) {
      if (mounted) setState(() => _assetChecked = true);
    }
  }

  void _startGeneration() {
    if (_generating || _generationFailed || _generated != null) return;
    setState(() => _generating = true);
    IconGeneratorService.generateIcon(widget.itemName).then((bytes) {
      if (!mounted) return;
      setState(() {
        _generated = bytes;
        _generating = false;
        _generationFailed = bytes == null;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    final radius = widget.borderRadius ?? BorderRadius.circular(10);

    return ClipRRect(
      borderRadius: radius,
      child: SizedBox(
        width: widget.size,
        height: widget.size,
        child: _buildContent(),
      ),
    );
  }

  Widget _buildContent() {
    // Tier 1: bundled asset
    if (_asset != null) {
      return Image.memory(_asset!, fit: BoxFit.cover);
    }

    // Still checking for asset — show placeholder
    if (!_assetChecked) {
      return _Placeholder(loading: true, itemName: widget.itemName, size: widget.size);
    }

    // Tier 3: Gemini-generated
    if (_generated != null) {
      return Image.memory(_generated!, fit: BoxFit.cover);
    }

    // Tier 2+: Firebase Storage. The exact-name object is what we upload now
    // and what the CH display board fetches; the lowercase ones are legacy
    // objects from before icons kept their capitals, kept as a fallback so
    // existing icons still show until they're regenerated.
    // Set literal: an already-lowercase name would otherwise repeat a URL.
    final urls = <String>{
      FridgeService.iconUrl(widget.itemName, extension: 'jpg'),
      FridgeService.iconUrl(widget.itemName,
          extension: 'jpg', legacyLowercase: true),
      FridgeService.iconUrl(widget.itemName,
          extension: 'png', legacyLowercase: true),
    }.toList();

    return _storageChain(urls, 0);
  }

  /// Try each Storage URL in order; when they all miss, fall through to Gemini
  /// generation and finally the coloured letter avatar.
  Widget _storageChain(List<String> urls, int i) {
    if (i >= urls.length) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _startGeneration());
      if (_generating) {
        return _Placeholder(
          loading: true,
          itemName: widget.itemName,
          size: widget.size,
          label: 'AI…',
        );
      }
      return _LetterAvatar(itemName: widget.itemName, size: widget.size);
    }
    return CachedNetworkImage(
      imageUrl: urls[i],
      fit: BoxFit.cover,
      fadeInDuration: const Duration(milliseconds: 200),
      placeholder: (_, __) => _Placeholder(
        loading: true,
        itemName: widget.itemName,
        size: widget.size,
      ),
      errorWidget: (_, __, ___) => _storageChain(urls, i + 1),
    );
  }
}

class _Placeholder extends StatelessWidget {
  final bool loading;
  final String itemName;
  final double size;
  final String? label;

  const _Placeholder(
      {required this.loading,
      required this.itemName,
      required this.size,
      this.label});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      color: AppColors.surfaceContainerHigh,
      child: loading
          ? Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  SizedBox(
                    width: size * 0.3,
                    height: size * 0.3,
                    child: const CircularProgressIndicator(
                        strokeWidth: 2, color: AppColors.primary),
                  ),
                  if (label != null) ...[
                    const SizedBox(height: 4),
                    Text(label!,
                        style: TextStyle(
                            fontSize: size * 0.15,
                            color: AppColors.primary,
                            fontWeight: FontWeight.w700)),
                  ]
                ],
              ),
            )
          : const Icon(Icons.fastfood_rounded, color: AppColors.outline),
    );
  }
}

class _LetterAvatar extends StatelessWidget {
  final String itemName;
  final double size;

  const _LetterAvatar({required this.itemName, required this.size});

  static const _colors = [
    Color(0xFF1A237E),
    Color(0xFF006E1C),
    Color(0xFF5B4300),
    Color(0xFF7B1FA2),
    Color(0xFF00695C),
    Color(0xFFBF360C),
    Color(0xFF1565C0),
    Color(0xFF2E7D32),
  ];

  Color get _bg {
    final idx =
        itemName.isNotEmpty ? itemName.codeUnitAt(0) % _colors.length : 0;
    return _colors[idx];
  }

  @override
  Widget build(BuildContext context) {
    final letter =
        itemName.isNotEmpty ? itemName[0].toUpperCase() : '?';
    return Container(
      width: size,
      height: size,
      color: _bg.withValues(alpha: 0.15),
      child: Center(
        child: Text(
          letter,
          style: TextStyle(
            fontSize: size * 0.4,
            fontWeight: FontWeight.w800,
            color: _bg,
          ),
        ),
      ),
    );
  }
}
